### PR TITLE
Addition of memphis.dev

### PR DESCRIPTION
**Pull request by yanivbh1**
Addition of memphis.dev writer program

### CODE REVIEW

**Comment by Goodnessuc** [comment]
Screenshot_20220713-212251_Chrome
The link doesn't work

**Comment by yanivbh1** [comment]
@Goodnessuc Thank you! Fixed.

**Comment by karllhughes** [comment]
@yanivbh1 could you also alphabetize this? Thanks!

**Comment by Qodestackr** [comment]
Mention payment options kindly? PayPal, bank? Etc. To me in Africa it does matter

**Comment by karllhughes** [comment]
Closing until we get a response from @yanivbh1.

**Comment by yanivbh1** [comment]
Hey @Qodestackr, @karllhughes,
Paypal / Stripe form.

**Comment by karllhughes** [comment]
@yanivbh1 we actually just need this alphabetized before we can merge it. Thanks!

**Comment by karllhughes** [comment]
@yanivbh1 if the program is still open and you'd like to resolve conflicts and alphabetize this, we can merge it. Let me know!

**Pull request closed without merging**
