### PR TITLE
add magicpod writers' program

### PR DESCRIPTION
**Pull request by oshorefueled**
This PR adds MagicPod writers' program to the list:  [Writer's Program](https://frost-act-be2.notion.site/MagicPod-Writers-Program-ea85c41d617943559a351f85c3add632)

[magicpod.com](magicpod.com)

### CODE REVIEW

**Review by john-walter-munene — APPROVED** [review]

**Comment by oshorefueled** [comment]
Thanks for approving @john-walter-munene

**Comment by chrisawoke** [comment]
Thanks, man. Great work!

**Comment by malgamves** [comment]
hey @oshorefueled a couple merge conflicts, happy to merge when you fix those.

**Comment by oshorefueled** [comment]
@malgamves Resolved! Thank you.

**Comment by malgamves** [comment]
Thanks, merging!

**Pull request merged**
