### PR TITLE
Added 3 Websites that accepts paid guest writing

### PR DESCRIPTION
**Pull request by rahxuls**

### CODE REVIEW

**Comment by karllhughes** [comment]
1. Do you know how much these programs pay? We like to include that info when possible.
2. Could you please alphabetize them in our list? This makes programs easier to find.

@malgamves any other comments?

**Comment by malgamves** [comment]
Nope! You pretty much covered it all @karllhughes 🙌

**Comment by Qodestackr** [comment]
Hey @karllhughes @malgamves which 3 webites ? Trying to apply all but no responses mostly.

**Comment by malgamves** [comment]
we usually like to have an idea of what they pay and how they interact with writers @Qodestackr so as soon as they respond and you get figures for how much they compensate, do add them here and we can merge the PR :D

**Comment by Qodestackr** [comment]
I Appreciate, I hope that the repo is still active. 👍

**Comment by rahxuls** [comment]
@Qodestackr @malgamves I tried contacting them too a month ago still no response. I guess you can remove my pull request. Let me research and open PR when I find something unique.

**Comment by malgamves** [comment]
no worries @rahxuls - always happy to get PRs :D

**Pull request closed without merging**
